apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: mongo-mongo-pacman-jzdi
  namespace: somalley-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:ra-CF-mongo-mongo-pacman-jzdi
        name: container-image
        resources: {}
status: {}
