apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: frontend-mongo-pacman-bwqt
  namespace: somalley-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:97825587a8cb9a6308873122c4fa7704f5c5458a9abea9064e8777518c41e475
        name: container-image
        resources: {}
status: {}
