apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: frontend-mongo-pacman-bwqt
  namespace: somalley-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:0bf3f934b6dacdee45cdd2bf5e200edd9fca280af9a22ed77945a75d4f207577
        name: container-image
        resources: {}
status: {}
